//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "pings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub tracker_id: u64,
    #[sea_orm(column_type = "Double", nullable)]
    pub lat: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub lon: Option<f64>,
    pub note: String,
    #[sea_orm(column_type = "Binary(16)", nullable)]
    pub uuid: Option<Vec<u8>>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::trackers::Entity",
        from = "Column::TrackerId",
        to = "super::trackers::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Trackers,
}

impl Related<super::trackers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trackers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
